#!/bin/bash
set -e

cd $3/$1

django-admin startapp $2

cd $2
mkdir -p $3/$1/$2/static/$2/images/
mkdir -p $3/$1/$2/static/$2/js/
mkdir -p $3/$1/$2/static/$2/scss/
mkdir -p $3/$1/$2/templates/$2/

cp $4/urls.template.py urls.py
cp $4/views.template.py views.py

sed "s/app_name/$2/g" $4/index.template.html > $3/$1/$2/templates/$2/index.html
sed "s/app_name/$2/g" $4/base.template.html > $3/$1/$2/templates/$2/base.html
cp $4/_navbar.template.html $3/$1/$2/templates/$2/_navbar.html 
cp $4/_navbar.template.scss $3/$1/$2/static/$2/scss/_navbar.scss
cp $4/application.template.scss $3/$1/$2/static/$2/scss/application.scss
cp $4/index.template.js $3/$1/$2/static/$2/js/index.js
